name: whisper-fine-tune-env
channels:
  - pytorch
  - nvidia # For CUDA toolkit if needed explicitly
  - defaults
  - conda-forge
dependencies:
  - python=3.9 # Or 3.8, 3.10
  - pip
  - pip:
    - transformers[torch]==4.35.0 # Or latest
    - datasets==2.14.0     # Or latest
    - evaluate==0.4.0      # Or latest
    - scikit-learn         # Often a dep for 'evaluate' or other metrics
    - accelerate==0.23.0   # Or latest, crucial for Trainer & fp16
    - azureml-mlflow       # For AML logging integration
    - joblib               # Sometimes a hidden dependency for datasets .map
    # - protobuf # Sometimes needed by transformers or onnx
